version: "3"
services: 
    db:
        build: mssqlserver
        ports:
            - "1433:1433"
        environment: 
            - ACCEPT_EULA=Y  
            - SA_PASSWORD=Password1!  
            - MSSQL_PID=Express
    api:
        build: UserManagementAPI/UserManagementAPI
        ports: 
            - "8080:80"